theme: jekyll-theme-minimal

# <COMMUNITY HOUSING AND TRAINING (CHT) PROGRAM > 

# **Program Summary

Kambantangan Sa Kapagongaya Peace Advocates, Inc. through its Community Housing and Training (CHT) Program initiates a low-cost housing project in the targeted area at Barangay Tamontaka 5, Cotabato City for its homeless members mostly low-income earner families particularly the poor who were affected and displaced because of the armed conflict between the government troops and rebel groups, living with extended relatives and informal settlers residing in the highly congested poor areas which could hardly be called a homes in this city.

The CHT Program will also provide occupational skills training for unskilled individuals and members of the family in order to enhance and to develop their capabilities and skills to augment their family income as well as basic educational services for less in education and school-age children and leadership development counseling and values formation for self-worth and dignity as human being and can be productive members of the society.

This proposal budget in the amount of PhP 1,704,000.00 for Non-Housing and Administrative Components of the CHT Program will be sourced out in the form of solicitation for program’s assistance to generous and interested Donors (Individuals and Groups, Philanthropists) who are willing to help us for these charitable activities. We anticipate the said assistance from the Donors which will be an essential and primary part of our program that permits our efforts in the field of skills training, education, social services, counseling and values formation.

The program which we ENVISION is multifaceted (means having a variety of different and important features or elements of the program, from sheltering, educational services, occupational/livelihood skills training and social services including counseling and values formation for self-worth as human being), comprehensive (means something that includes everything that is needed or relevant, programs that are complementary to each other in a typical community from educational, economic to social services) and innovative (something that is new and original, programs’ approaches which are more innovative than those of their competitions, like; approaches to educational services outside of the formal school, It introduces changes and new ideas which are believed to be effective in today’s complex driven environment).

The organization has already identified and acquired a 2-hectare land area for the housing site as a component of this program through our initiatives and voluntary contributions.

Although, we have generous friends within the community support our programs, however due to the overall cumulative effect of the economy, we have been unable to secure the essential funding for the Community Housing and Training (CHT) Programs and Projects.

With this reality, I decided to open another window of opportunities to seek any amount as voluntary contribution and  support for the COMMUNITY HOUSING AND TRAINING (CHT) PROGRAM from a generous friend like you with heart for charitable activities. I strongly believed when your 1 Peso is added to my 1 Peso and added to our 1 Peso would be a big deal for the continuous implementation of CHT Programs and Projects, and thus be a part for the realization of program's Vision, Mission and Goals.

The housing component will provide aid not only to those families requiring assisted housing but also to those families who are direct beneficiaries of non-housing component of the CHT program. We anticipate that percentage of the units will be set aside for school buildings, values formation center, multi-purpose center and office.

# Vision

The program which we ENVISION is multifaceted (means having a variety of different and important features or elements of the program, from sheltering, educational services, occupational/livelihood skills training and social services including counseling and values formation for self-worth as human being), comprehensive (means something that includes everything that is needed or relevant, programs that are complementary to each other in a typical community from educational, economic to social services) and innovative (something that is new and original, programs’ approaches which are more innovative than those of their competitions, like; approaches to educational services outside of the formal school, It introduces changes and new ideas which are believed to be effective in today’s complex driven environment).

The Housing Component will provide aid not only to those families requiring assisted housing but also to those families who are direct beneficiaries of non-housing component of the CHT program. We anticipate that percentage of the units will be set aside for school buildings, values formation center and multi-purpose center and office.

# Project Description

The project calls for the ACQUISITION OF LAND WITH THE PROVISION OF LOW-COST HOUSING for the NINETY (90) families or THREE HUNDRED SIXTY (360) individuals including members of the family of the organization, all of them are classified as among the “LOW-INCOME earners or the poor.”

## Prioritization of Needs

The LAND – The organization has identified the problem of land acquisition as its PRIORITY. The land where this is being settled is already acquired by the organization through our initiatives and voluntary contributions. With a total land area of 20,000 square meters, 14,000 square meters will be allotted for housing. This represents 70% of the total land area. The other 30% of the land or 6,000 square meters is for roads, parks or open space as required by law and multi-purpose center, values formation center and school buildings.

The DWELLING UNITS. The construction of dwelling units for the members is the second priority need of the organization. Considering the lack of funds, the members, however, could temporarily make use of already available materials for the construction of their temporary dwelling units, while the organization is seeking out for the construction costs of the housing project to interested donors, philanthropists and generous individuals or groups. 

Moreover, the organization is committed to shoulder the administrative costs and expenses, examples; survey cost, titling and registration, taxes and regulatory fees.

Nevertheless, if ever funds would be available, the organization is willing to shoulder the labor cost in the construction of the houses.

The organization is contemplating on the MEDIUM-RISE HOUSING MODEL (One Storey Residential Building). The model has an estimated minimum construction cost of ONE HUNDRED FIFTY THOUSAND PESOS (P150,000.00).

# Program Goals and Objectives

## General:

To provide assisted housing, occupational/livelihood skills training as well as basic educational services and leadership development counseling and  values formation to conflict affected families, who are living with extended relatives, no permanent house, low-income earners with less in education and livelihood skills.

## Specific:

To transform socially and improve the quality of life of the member-beneficiaries through life-long learning;

To cater to the learning and training needs of the members, peer meeting, education, values formation, livelihood training and other group activities;

To serve as a venue to preserve, strengthen, and promote desired culture and integrate them towards the attainment of cultural understanding, unity and cooperation;

To serve as a venue to train and upgrade the skills of religious preachers, teachers, trainers, facilitators and other persons involved in education activities;

To serve as a venue for values formation, teaching and other organizational activities such as organization meeting, planning and evaluation, committee meeting;

To serve as a vehicle to generate funds and sustain the management and maintenance of the Multi Purpose Center;

To serve as a venue to establish and strengthen linkages and network among NGOs, POs, GOs engaged in same activities;

To provide educational services outside of the formal school for the members to have a pre knowledge and skills in understanding the expected belief for their life;

To be able to inculcate in the minds of the member-beneficiaries the standard norms, desired values and  culture, self-worth, importance of human dignity and hopes for a brighter future;

To provide the family members with occupational skills to enhance their capability and skills in order to augment their family income; and

To be able to become a good model in leading and abiding the expected standard norms in the community and become productive members of the society.

# Program Results

### Job Placement and Post-Graduation Follow-up

The one-year CHT Program will offer participants a solid cognitive, developmental, and experiential foundation for future life and work. However, training and education require substantive follow-up of job placement and continuing counselling services for program graduates.

During the last month of the CHT Program, as participants focus on interview and oral written skills (development of resume) in their speech, writing and leadership counselling classes, they will become familiar with job in the locality. Applicants will receive support in the form of counselling services as appropriate.

Measurable objectives will be achieved by the number of participants who are recruited and who complete the application process. In addition for each class and the training sessions, attendance will be taken. Attendance will measure the degree of program success. No applicant will be permitted to graduate without attending 90% of the session in each area.

Upon acceptance into the program, each student will be given a traditional placement exam, the scores of which will be compared with the scores upon graduation.

Job and higher education placement will be recorded with follow-up after one year of the exiting of the individual students. Follow-up counselling will be made available.

Completion rate of housing will be judged by unit occupancy after one year from the start of the program.

### Program Linkages




