theme: jekyll-theme-merlot

# COMMUNITY HOUSING AND TRAINING (CHT) PROGRAM  

## Program Summary

'**Background**'

'**The Emergence of the COMMUNITY HOUSING AND TRAINING (CHT) PROGRAM**'

'The emergence of the COMMUNITY HOUSING AND TRAINING (CHT) PROGRAM is out of our social concerns on the low-income earner families particularly who were affected by armed conflicts between the gov’t troops and rebel groups, who are living with extended relatives, no permanent house and anywhere in this city and nearby areas, who are classified as low-income earners, with less education and livelihood skills and through series of studies with a group of Professionals and friends from different sectors of society but with one common objective; to help the needy.'






